/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ruben.pe.cprecentacion;

import java.awt.BorderLayout;

/**
 *
 * @author ACER
 */
public class JframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JframePrincipal
     */
    public JframePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btncalculadora = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnMenuContador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        DATOSDOCUMENTO = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnmenupersonadocumento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aplicacion java");

        principal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 0));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 0));
        jMenuBar1.setOpaque(true);

        btncalculadora.setText("aplicaciones");

        jMenuItem1.setText("calculadora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btncalculadora.add(jMenuItem1);

        btnMenuContador.setText("contador");
        btnMenuContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContadorActionPerformed(evt);
            }
        });
        btncalculadora.add(btnMenuContador);

        jMenuBar1.add(btncalculadora);

        jMenu2.setText("Edit");

        jMenu1.setText("jMenu1");
        jMenu2.add(jMenu1);

        jMenuBar1.add(jMenu2);

        DATOSDOCUMENTO.setText("mantenimiento");

        jMenuItem2.setText("Datos_documento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        DATOSDOCUMENTO.add(jMenuItem2);

        jMenuItem3.setText("Datos de la tarjeta ");
        DATOSDOCUMENTO.add(jMenuItem3);

        jMenuItem4.setText("Documento de identidad ");
        DATOSDOCUMENTO.add(jMenuItem4);

        btnmenupersonadocumento.setText("personadocumento");
        btnmenupersonadocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenupersonadocumentoActionPerformed(evt);
            }
        });
        DATOSDOCUMENTO.add(btnmenupersonadocumento);

        jMenuBar1.add(DATOSDOCUMENTO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContadorActionPerformed
        // TODO add your handling code here:
     contador con = new contador();
     con.setSize(435, 587);
     con.setLocation(0,0);
     principal.removeAll();
     principal.add(con,BorderLayout.CENTER);
     principal.revalidate();
     principal.repaint();
    }//GEN-LAST:event_btnMenuContadorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        
     calculadora c = new calculadora  ();
     c.setSize(435, 651);
     c.setLocation(0,0);
     principal.removeAll();
     principal.add(c,BorderLayout.CENTER);
     principal.revalidate();
     principal.repaint();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
     jpDatos_Documento DD = new jpDatos_Documento();
     DD.setSize(1100, 600);
     DD.setLocation(0,0);
     principal.removeAll();
     principal.add(DD,BorderLayout.CENTER);
     principal.revalidate();
     principal.repaint();
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnmenupersonadocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenupersonadocumentoActionPerformed
        // TODO add your handling code here:
        
        jpPersonaDocumento DD = new jpPersonaDocumento();
     DD.setSize(1000, 500);
     DD.setLocation(0,0);
     principal.removeAll();
     principal.add(DD,BorderLayout.CENTER);
     principal.revalidate();
     principal.repaint();
        
        
        
    }//GEN-LAST:event_btnmenupersonadocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DATOSDOCUMENTO;
    private javax.swing.JMenuItem btnMenuContador;
    private javax.swing.JMenu btncalculadora;
    private javax.swing.JMenuItem btnmenupersonadocumento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
