/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ruben.pe.cprecentacion;

import com.ruben.pe.cmodelo.Datos_Documento;
import com.ruben.pe.cnegocio.Datos_DocumentoBO;
import com.ruben.pe.ctest.Test;
import java.text.ParseException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class jpDatos_Documento extends javax.swing.JPanel {
    Datos_DocumentoBO tdbo = new Datos_DocumentoBO() ;
    Datos_Documento dd = new Datos_Documento();
    String idDatosdocumento;

    /**
     * Creates new form jpDatos_Documento
     */
    public jpDatos_Documento() {
        initComponents();
        listarDatos_Documento ();
    }
    
    public void listarDatos_Documento  (){
        tdbo.listarDatos_Documento(tablaDatosDocumento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudDatosDELdocumento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosDocumento = new javax.swing.JTable();
        BTNeliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        TextNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        TextFechaEmicion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        TEXTfechavencimiento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        TextIDcliente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        TextIDDocumentoIdentidad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BtnGuardar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();

        crudDatosDELdocumento.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Short Plan", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 239, 90));
        jLabel1.setText("CRUD Datos del Documento");

        jScrollPane1.setForeground(new java.awt.Color(102, 102, 255));

        tablaDatosDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDatosDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosDocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatosDocumento);

        BTNeliminar.setText("Eliminar");
        BTNeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeliminarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        TextNumero.setBackground(new java.awt.Color(0, 153, 153));
        TextNumero.setBorder(null);
        TextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumeroActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Numero");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Emicion");

        TextFechaEmicion.setBackground(new java.awt.Color(0, 153, 153));
        TextFechaEmicion.setBorder(null);
        TextFechaEmicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFechaEmicionActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de vencimiento");

        TEXTfechavencimiento.setBackground(new java.awt.Color(0, 153, 153));
        TEXTfechavencimiento.setBorder(null);
        TEXTfechavencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTfechavencimientoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("El ID del Cliente");

        TextIDcliente.setBackground(new java.awt.Color(0, 153, 153));
        TextIDcliente.setBorder(null);
        TextIDcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDclienteActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("El ID de documento de identidad");

        TextIDDocumentoIdentidad.setBackground(new java.awt.Color(0, 153, 153));
        TextIDDocumentoIdentidad.setBorder(null);
        TextIDDocumentoIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDDocumentoIdentidadActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crudDatosDELdocumentoLayout = new javax.swing.GroupLayout(crudDatosDELdocumento);
        crudDatosDELdocumento.setLayout(crudDatosDELdocumentoLayout);
        crudDatosDELdocumentoLayout.setHorizontalGroup(
            crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel1))
                    .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                        .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addComponent(jSeparator1))
                                    .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFechaEmicion)
                                        .addComponent(jLabel3)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TEXTfechavencimiento)
                                        .addComponent(jLabel4)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextIDcliente)
                                        .addComponent(jLabel5)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextIDDocumentoIdentidad)
                                        .addComponent(jLabel6)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crudDatosDELdocumentoLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(BtnLimpiar)
                                .addGap(67, 67, 67)
                                .addComponent(BtnGuardar)))
                        .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(BtnModificar)
                                .addGap(151, 151, 151)
                                .addComponent(BTNeliminar))
                            .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        crudDatosDELdocumentoLayout.setVerticalGroup(
            crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFechaEmicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXTfechavencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextIDDocumentoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardar)
                            .addComponent(BtnLimpiar)))
                    .addGroup(crudDatosDELdocumentoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(crudDatosDELdocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnModificar)
                    .addComponent(BTNeliminar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crudDatosDELdocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crudDatosDELdocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumeroActionPerformed
        // TODO add your handling code here:
        TextNumero.getText();
    }//GEN-LAST:event_TextNumeroActionPerformed

    private void TextFechaEmicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFechaEmicionActionPerformed
        // TODO add your handling code here:
        TextFechaEmicion.getText();
    }//GEN-LAST:event_TextFechaEmicionActionPerformed

    private void TEXTfechavencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTfechavencimientoActionPerformed
        // TODO add your handling code here:
        TEXTfechavencimiento.getText();
    }//GEN-LAST:event_TEXTfechavencimientoActionPerformed

    private void TextIDclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDclienteActionPerformed
        // TODO add your handling code here:
        TextIDcliente.getText();
    }//GEN-LAST:event_TextIDclienteActionPerformed

    private void TextIDDocumentoIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDDocumentoIdentidadActionPerformed
        // TODO add your handling code here:
        TextIDDocumentoIdentidad.getText();
    }//GEN-LAST:event_TextIDDocumentoIdentidadActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
         try {
        // Crear un objeto Datos_Documento
        Datos_Documento dd = new Datos_Documento();
        
        // Obtener los valores de los campos de texto del formulario
        dd.setNumero(Integer.parseInt(TextNumero.getText()));
        dd.setFecha_Emicion(TextFechaEmicion.getText());
        dd.setFecha_Vencimiento(TEXTfechavencimiento.getText());
        dd.setId_cliente(Integer.parseInt(TextIDcliente.getText()));
        dd.setID_DOCUMENTO_IDENTIDAD(Integer.parseInt(TextIDDocumentoIdentidad.getText()));
        
        // Crear un objeto de negocio y llamar al método para agregar datos
        Datos_DocumentoBO tdbo = new Datos_DocumentoBO();
        String mensaje = tdbo.agregarDatosDocumento(dd);
        listarDatos_Documento();
        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, mensaje);
        
        // Limpiar los campos de texto después de guardar
        limpiarCampos();
        
    } catch (SQLException | ParseException e) {
        // Manejo de excepciones
        JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
    } catch (NumberFormatException e) {
        // Manejo de excepciones para formato de número
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.");
    }
        
        
        
        
        
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        TextNumero.setText("");
    TextFechaEmicion.setText("");
    TEXTfechavencimiento.setText("");
    TextIDcliente.setText("");
    TextIDDocumentoIdentidad.setText("");
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void tablaDatosDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosDocumentoMouseClicked
        // TODO add your handling code here:
        int seleccion  = tablaDatosDocumento.rowAtPoint(evt.getPoint());
        idDatosdocumento = tablaDatosDocumento.getValueAt(seleccion, 0)+"";
        
        
        TextNumero.setText(tablaDatosDocumento.getValueAt(seleccion, 1)+"");
        TextFechaEmicion.setText(tablaDatosDocumento.getValueAt(seleccion, 2)+"");
        TEXTfechavencimiento.setText(tablaDatosDocumento.getValueAt(seleccion, 3)+"");
        TextIDcliente.setText(tablaDatosDocumento.getValueAt(seleccion, 4)+"");
        TextIDDocumentoIdentidad.setText(tablaDatosDocumento.getValueAt(seleccion, 5)+"");
        System.out.println(seleccion);
    }//GEN-LAST:event_tablaDatosDocumentoMouseClicked

    private void BTNeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeliminarActionPerformed
        if (idDatosdocumento != null && !idDatosdocumento.isEmpty()) {
            try {
                // Establecer el ID del documento a eliminar
                dd.setId_Datos_Documento(Integer.parseInt(idDatosdocumento));
                
                // Llamar al método de negocio para eliminar el documento
                String mensaje = tdbo.eliminarDatosDocumento(dd);
                
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, mensaje);
                
                listarDatos_Documento();

                
                // Limpiar campos
                limpiarCampos();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: ID no válido.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para eliminar.");
        }
    }//GEN-LAST:event_BTNeliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        if (idDatosdocumento != null && !idDatosdocumento.isEmpty()) {
        try {
            dd.setId_Datos_Documento(Integer.parseInt(idDatosdocumento));
            dd.setNumero(Integer.parseInt(TextNumero.getText())); 
            dd.setFecha_Emicion(TextFechaEmicion.getText()); 
            dd.setFecha_Vencimiento(TEXTfechavencimiento.getText()); 
            dd.setId_cliente(Integer.parseInt(TextIDcliente.getText())); 
            dd.setID_DOCUMENTO_IDENTIDAD(Integer.parseInt(TextIDDocumentoIdentidad.getText())); 
            
            String mensaje = tdbo.modificarDatosDocumento(dd);
            
            JOptionPane.showMessageDialog(this, mensaje);
            
            listarDatos_Documento();
            
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique que todos los campos sean válidos.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para modificar.");
    }
    }//GEN-LAST:event_BtnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNeliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JTextField TEXTfechavencimiento;
    private javax.swing.JTextField TextFechaEmicion;
    private javax.swing.JTextField TextIDDocumentoIdentidad;
    private javax.swing.JTextField TextIDcliente;
    private javax.swing.JTextField TextNumero;
    private javax.swing.JPanel crudDatosDELdocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tablaDatosDocumento;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
    TextNumero.setText("");
    TextFechaEmicion.setText("");
    TEXTfechavencimiento.setText("");
    TextIDcliente.setText("");
    TextIDDocumentoIdentidad.setText("");    }
}

